image: node:7.0.0
pipelines:
  default:
    - step:
        script:
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn
          - yarn test